name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    name: Build and release

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build NumerazioneProtocollo.sln /p:DeployOnBuild=true /p:Configuration=Release /p:Platform="x64" /p:PublishProfile=Properties/PublishProfiles/linux-x64.pubxml

    - name: Get current date
      continue-on-error: true
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"

    - name: Create GitHub Release
      if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      uses: softprops/action-gh-release@v1
      with:
        files: "/home/runner/work/NumerazioneProtocollo/NumerazioneProtocollo/bin/Release/net6.0/NumerazioneProtocollo.zip"
        tag_name: ${{ steps.date.outputs.date }}
        token: ${{ secrets.RELEASES_TOKEN }} 
   


  
  

